apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
data:
  DB_HOST: "ecommerce-db"

  init.sql: |
    CREATE TABLE IF NOT EXISTS orders (
      id SERIAL PRIMARY KEY,
      item VARCHAR(100),
      qty INT,
      address TEXT,
      seller VARCHAR(100) DEFAULT 'Flipkart'
    );